#!/bin/sh
# Automatically setup external monitor

xrandr_command="/usr/bin/xrandr"
sed_command="/bin/sed"

is_hdmi_connected=`DISPLAY=:0 $xrandr_command | $sed_command -n '/DP1 connected/p'`

if [ -n "$is_hdmi_connected" ]; then
  DISPLAY=:0 $xrandr_command --output DP1 --auto --output eDP1 --off
else
  DISPLAY=:0 $xrandr_command --output DP1 --off
fi
