#!/usr/bin/env bash

# Created by Dylan Araps

# Set to nothing to disable bold text
bold=$(tput bold)

# Clears attributes
clear=$(tput sgr0)

# Default color
# colors are now defined with a launch option "-c"
color=$(tput setaf 1)

title="          $(whoami)          "
# title="Unicorn"

# Custom text to print at the bottom, configurable at launch with "-e"
#customtext=$(colors2.sh)

# Set up args
while getopts ":c:e:w:h:t:p:x:y:" opt; do
    case $opt in
        c) color=$(tput setaf $OPTARG) ;;
        e) customtext="$OPTARG" ;;
        w) width="$OPTARG" ;;
        h) height="$OPTARG" ;;
        t) title="$OPTARG" ;;
        p) pad="$OPTARG" ;;
        x) xoffset="$OPTARG" ;;
        y) yoffset="$OPTARG" ;;
    esac
done

# Underline title with length of title
underline=$(printf %"${#title}"s |tr " " "-")

# Start printing info

# Clear terminal before running
clear


echo "${pad}${bold}$title${clear}"
echo "${pad}$underline"
echo "    ${pad}${bold}${color}os${clear} : $(cat /etc/*ease | awk '/^NAME=/' | cut -d '"' -f2)"
echo "  ${pad}${bold}${color}krnl${clear} : $(uname -r)"
echo "   ${pad}${bold}${color}upt${clear} : $(uptime -p | sed -e 's/minutes/mins/')"
echo "  ${pad}${bold}${color}pack${clear} : $(pacman -Q | wc -l)"
echo "  ${pad}${bold}${color}shel${clear} : $SHELL"
echo "    ${pad}${bold}${color}wm${clear} : i3"
echo "   ${pad}${bold}${color}cpu${clear} : i7-5500U CPU 3$(lscpu | awk '/CPU MHz:/ {printf "scale=1; "" / 1000 \n"}' | bc -l)GHz"
echo "   ${pad}${bold}${color}ram${clear} : $(free -m | awk '/Mem:/ {printf $3 "MB / " $2 "MB"}')"
echo "  ${pad}${bold}${color}strg${clear} : $(df -h /dev/sdb2 | awk '/dev/ {print $3 " / " $2}')"
